### ISSUE TITLE
Learn Generates Probabilities of 1.0 for Each Call 

### ISSUE THREAD

**Issue by apython1998** [ptnplanet/Java-Naive-Bayes-Classifier#15]
For each learn call, the probability that a category happens is set to 1.0. This in turn makes every classify be whatever the last learn's category was.

**Comment by ptnplanet** [comment]
Hi @apython1998. Can you give me an example for this behavior? If I understand your issue description correctly, this would mean that the runnable example would only produce classifications for the "negative" category... which it does not. Please share more details so that I can dive into the issue you are experiencing. Thanks & cheers

**Comment by apython1998** [comment]
Misread it in the debugger, I'll close the issue. My apologies.

Thanks you.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
