### ISSUE TITLE
Store Classifier

### ISSUE THREAD

**Issue by dtitov** [ptnplanet/Java-Naive-Bayes-Classifier#2]
Is it possible to save/load (maybe some kind of serialization/deserialization) the trained classifier?

**Comment by ChaoMai** [comment]
I think it is possible to save them.

All learned data are stored in `featureCountPerCategory`, `totalFeatureCount`, `totalCategoryCount` and `memoryQueue`. So you just need to save/load them.

The reason:
1. You can analysis variables are used to store related data from the `learn()` method at line 376 in Classifier.java.
2. But there is another simple way.
* Take a look at line 65 and line 72 in Classifier.java. The `reset()` is invoked when `Classifier` is initialized. Since `BayesClassifier` is extends from `Classifier` and doesn't have is now constructor, `reset()` also will be invoked.
* In `reset()` method, `featureCountPerCategory`, `totalFeatureCount`, `totalCategoryCount` and `memoryQueue` are given new instance. So they should be the variables holding all learned data.

**Comment by dtitov** [comment]
Great, thanks.
